controllers/home.py
"""
Copyright 2005-2018 QuantumRocket. All rights reserved.
Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file.
"""
from typing import Optional, Dict, Any

import lib.log as log
import sql.db_things as db_things
import sql.db_users as db_users
import sql.db_widgets as db_widgets

from flask import request, redirect, session, render_template, url_for, flash, Blueprint

home = Blueprint('home', __name__, template_folder="templates")


@home.route('/')
@home.route('/index')
def index():
    """
    Home page.
    """

    things = None
    user = None

    try:

        things: Optional[Dict[Any, Any]] = db_things.get('page.index.help')

        user_email = session.get('user_email')
        user = None

        if user_email is None:

            # non-user: show help
            things['pref_show_page_help'] = 'yes'

        else:

            user = db_users.find_by_email(user_email)

            if user is None:
                things['pref_show_page_help'] = 'yes'
            else:
                if user['pref_show_page_help'] == 'yes':
                    things['pref_show_page_help'] = 'yes'

        return render_template('index.html', things=things, user=user)

    except Exception as e:

        log.error('home.py::index', 'Error on home page, [' + str(e) + '].')
        flash('Oops! Something went sideways. We have been notified of the problem. Carry on.')
        return render_template('index.html', things=things, user=user)


@home.route('/sign_in', methods=['POST'])
def sign_in():
    """
    Sign a user in.
    """

    user_email = request.form['user_email']
    password = request.form['password']

    user = db_users.auth_by_email_and_password(user_email, password)

    if not user:
        log.alert('home.py::sign_in', 'Failed sign in attempt for email [' + user_email + '].')
        flash('Could not sign you in. Are you already a user? If not, please sign up.')
        return redirect(url_for('home.index'))

    session['authenticated'] = True
    session['user_email'] = user_email
    session['user_id'] = user['user_id']

    flash('Welcome back ' + user['full_name'] + '!')

    return redirect(url_for('home.dashboard'))


@home.route('/sign_up', methods=['POST'])
def sign_up():
    """
    Sign up a new user.
    """

    user_email = request.form['user_email']
    password = request.form['password']
    
    user = db_users.find_by_email(user_email)
    if user is not None:
        flash('A user with that email address already exists. Hmmm. Not you? Try another email address.')
        return redirect(url_for('home.index'))
    
    user = db_users.insert_user(user_email, password)

    if user is None:
        flash('Oops! Looks like something went sideways. We have been notified of the problem. Carry on.')
        return redirect(url_for('home.index'))

    session['authenticated'] = True
    session['user_email'] = user_email
    session['user_id'] = user['user_id']

    flash('Welcome to QuantumRocket!')

    return redirect(url_for('home.dashboard'))


@home.route('/sign_out', methods=['GET'])
def sign_out():
    """
    Sign a user out.
    """

    session.clear()

    return redirect(url_for('home.index'))


@home.route('/dashboard', methods=['GET'])
def dashboard():
    """
    The Dashboard displays all stats at a glance.
    """

    user_email = session.get('user_email')
    user = db_users.find_by_email(user_email)
    
    if user is None:
        log.error('home.py::dashboard', 'No user record for email [' + user_email + '].')
        flash('Oops! Looks like something went sideways. We have been notified of the problem. Carry on.')
        return redirect(url_for('home.index'))
        
    widgets = db_widgets.find_by_user_id(user['user_id'])
    things: Optional[Dict[Any, Any]] = db_things.get('page.dashboard.help')

    if user['pref_show_page_help'] == 'yes':
        things['pref_show_page_help'] = 'yes'

    return render_template('dashboard.html', widgets=widgets, things=things)

controllers/profile.py
"""
Copyright 2005-2018 QuantumRocket. All rights reserved.
Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file.
"""

import lib.kvpairs as kvpairs
import lib.log as log
import sql.db as db
import sql.db_things as db_things
import sql.db_users as db_users

from flask import request, redirect, session, render_template, url_for, flash, Blueprint
from typing import Optional, Dict, Any, Union


profile = Blueprint('profile', __name__, template_folder="templates")
cfg = kvpairs.load(kvpairs.get_config_filename())


@profile.route('/my_profile', methods=['GET'])
def my_profile():
    """
    Display a user's profile.
    """

    try:

        user_email = session.get('user_email')
        user = db_users.find_by_email(user_email)

        things = db_things.get('page.my_profile.help')

        if user['pref_show_page_help'] == 'yes':
            things['pref_show_page_help'] = 'yes'

        return render_template('my_profile.html', user=user, things=things)

    except Exception as e:
        log.error('profile.py::my_profile', str(e))
        return redirect(url_for('home.dashboard'))


def get_user_from_request(req):
    """
    Create a user (in memory) from a request. This is used by update_profile
    if there is an error processing the user's input and we want to restore the
    user's input when rendering the my_profile.html page.
    """

    try:

        user: Dict[str, Union[str, Any]] = {}

        user['user_id'] = req.form['user_id']
        user['full_name'] = req.form['full_name']
        user['email'] = req.form['email']
        user['phone'] = req.form['phone']

        form = request.form
        pref_show_page_help = ''

        try:
            pref_show_page_help = form.getlist('pref_show_page_help')
        except Exception:
            log.debug('profile.py::get_user_from_request', 'pref_show_page_help NOT selected')

        if len(pref_show_page_help) > 0:
            user['pref_show_page_help'] = 'yes'
        else:
            user['pref_show_page_help'] = 'no'

        return user

    except Exception as e:

        log.error('profile.py::get_user_from_request', str(e))
        return None


@profile.route('/update_profile', methods=['POST'])
def update_profile():
    """
    Update a user's profile.
    """

    user_id = session.get('user_id')
    user_email = session.get('user_email')

    user = db_users.find_by_email(user_email)

    if user is None:
        log.error('profile.py::update_profile', 'ERROR: invalid state - no user record for user_email: ' + user_email)
        return redirect(url_for('home.index'))

    user_from_form: Optional[Dict[str, Union[str, Any]]] = get_user_from_request(request)

    # if the user is changing his/her email address,
    # check to make sure is doesn't already exist in the database

    if user_from_form['email'] != user_email:

        # check to see if the email address already exists
        check_email_user = db_users.find_by_email(user_from_form['email'])

        # if the email address is already taken, bail
        if check_email_user is not None:
            
            flash("The email address '" + user_from_form['email']
                  + "' is already in our system. Please try another email address.")

            return render_template('my_profile.html', user=user_from_form)

    user['email'] = user_from_form['email']
    user['full_name'] = user_from_form['full_name']
    user['phone'] = user_from_form['phone']
    user['pref_show_page_help'] = user_from_form['pref_show_page_help']

    db.update('users', {'user_id': user_id}, user)

    flash('Your profile changes were successful.')

    # if the user has changed their email address, update it in their session
    if user_from_form['email'] != user_email:

        session['user_email'] = user_from_form['email']

    return redirect(url_for('profile.my_profile'))

controllers/widget.py
"""
Copyright 2005-2018 QuantumRocket. All rights reserved.
Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file.
"""

import lib.log as log
import sql.db as db
import sql.db_users as db_users
import sql.db_widgets as db_widgets
import sql.db_things as db_things

from flask import request, redirect, session, render_template, url_for, flash, Blueprint
from typing import Optional, Dict, Any


widget = Blueprint('widget', __name__, template_folder="templates")


@widget.route('/my_widgets', methods=['GET'])
def my_widgets():
    """
    Display a user's widgets.
    """

    widgets = []
    user = None

    try:

        user_email = session.get('user_email')

        user = db_users.find_by_email(user_email)

        if user is None:
            log.error('widget.py::my_widgets', 'ERROR: invalid state - no user record for user_email: ' + user_email)
            flash('Please sign in. If you are not already a QuantumRocket user, please sign up.')
            return redirect(url_for('home.index'))

        widgets = db_widgets.find_by_user_id(user['user_id'])

    except Exception as e:

        log.error('widget.py::my_widgets', str(e))

    things = db_things.get('page.my_widgets.help')

    if user['pref_show_page_help'] == 'yes':
        things['pref_show_page_help'] = 'yes'

    return render_template('my_widgets.html', widgets=widgets, things=things)


def get_widget_from_request(req):
    """
    Create a widget (in memory) from a request. This is used if there is an error
    processing the user's input and we want to restore the user's input when
    rendering the add_widget.html page.
    """

    try:

        widget_from_request: Dict[str, Optional[Any]] = {}

        try:
            widget_from_request['widget_id'] = req.form['widget_id']
        except Exception:
            # if we are adding a new widget, there will not be a widget_id
            widget_from_request['widget_id'] = None

        widget_from_request['widget_name'] = req.form['widget_name']
        widget_from_request['description'] = req.form['description']

        return widget_from_request

    except Exception as e:

        log.error('widget.py::get_widget_from_request', str(e))
        return None


@widget.route('/add_widget', methods=['GET'])
def add_widget():
    """
    Start the process of adding a new widget.
    """

    return render_template('add_widget.html', widget=None)


@widget.route('/add_widget_complete', methods=['POST'])
def add_widget_complete():
    """
    Complete the process of adding a new widget.
    """

    user_id = session.get('user_id')
    user_email = session.get('user_email')

    user = db_users.find_by_email(user_email)

    if user is None:

        log.error('widget.py::add_widget_complete',
                  'ERROR: invalid state - no user record for user_email: ' + user_email)

        flash('Please sign in. If you are not already a QuantumRocket user, please sign up.')
        return redirect(url_for('home.index'))

    widget_name = request.form['widget_name']

    # check to see if the widget name already exists
    existing_widget: Optional[Dict[Any, Any]] = \
        db_widgets.find_by_user_id_and_widget_name(user_id, widget_name)

    if existing_widget is not None:

        flash("You already have a Widget with the name '" + widget_name
              + "'. Please try a different name as Widget names are unique.")

        keep_widget: Optional[Dict[str, Optional[Any]]] = get_widget_from_request(request)
        return render_template('add_widget.html', widget=keep_widget)

    description = request.form['description']

    widget = {}
    widget['widget_name'] = request.form['widget_name']
    widget['user_id'] = user_id
    widget['user_email'] = user_email
    widget['description'] = description

    widget_id = db.insert('widgets', widget)

    flash("Widget '" + widget_name + "' added.")
    log.debug('widget.py::add_widget_complete', 'Added new widget, widget_id [' + widget_id + '].')
    
    return redirect(url_for('widget.my_widgets'))


@widget.route('/delete_widget', methods=['POST'])
def delete_widget():
    """
    Delete a widget.

    This endpoint is called by the 'delete' action button,
    from the 'widgets' table on the my_widgets.html page.
    """

    widget_id = request.form['widget_id']
    log.debug('widget.py::delete_widget', 'widget_id [' + widget_id + ']')

    widget_to_delete: Optional[Dict[Any, Any]] = db_widgets.find_by_id(widget_id)
    widget_name = widget_to_delete['widget_name']

    # now we can safely delete the widget
    db_widgets.delete_widget(widget_id)

    flash("Widget name '" + widget_name + "' has been deleted.")
    log.debug('widget.py::delete_widget', 'deleted widget, widget_id [' + widget_id + ']')

    return redirect(url_for('widget.my_widgets'))


@widget.route('/edit_widget', methods=['GET'])
def edit_widget():
    """
    Edit a widget.

    This endpoint is called by an 'edit' action button,
    from the 'widgets' table on the my_widgets.html page.
    """

    user_id = session.get('user_id')
    user_email = session.get('user_email')

    user = db_users.find_by_email(user_email)

    if user is None:
        log.error('widget.py::edit_widget', 'ERROR: invalid state - no user record for user_email: ' + user_email)
        flash('Please sign in. If you are not already a user, please sign up.')
        return redirect(url_for('home.index'))

    widget_id = request.args.get('widget_id')

    if widget_id is None:

        log.error('widget.py::edit_widget',
                  'ERROR: invalid state - no widget_id in request. user_id [' + user_id + ']')

        flash('Oops! Something went sideways. We have been notified of the problem. Carry on.')
        return redirect(url_for('widget.my_widgets'))

    log.debug('widget.py::edit_widget', 'widget_id [' + widget_id + ']')

    widget_to_edit: Optional[Dict[Any, Any]] = db_widgets.find_by_id(widget_id)

    if widget_to_edit is None:

        log.error('widget.py::edit_widget',
                  'ERROR: invalid state - no widget record for widget_id [' + widget_id + ']')

        flash('Oops! Something went sideways. We have been notified of the problem. Carry on.')
        return redirect(url_for('widget.my_widgets'))

    return render_template('edit_widget.html', widget=widget_to_edit)


@widget.route('/edit_widget_complete', methods=['POST'])
def edit_widget_complete():
    """
    Complete a widget edit.
    """

    widget_id = request.form['widget_id']
    widget_name = request.form['widget_name']
    description = request.form['description']

    user_id = session.get('user_id')
    user_email = session.get('user_email')

    user = db_users.find_by_email(user_email)

    if user is None:

        log.error('widget.py::edit_widget_complete',
                  'ERROR: invalid state - no user record for user_email: ' + user_email)

        flash('Please sign in. If you are not already a user, please sign up.')
        return redirect(url_for('home.index'))

    # check to see if the widget name already exists
    existing_widget = db_widgets.find_by_user_id_and_widget_name(user_id, widget_name)

    if existing_widget is not None:

        # are we looking at the same widget (database and form)?
        if existing_widget['widget_id'] != widget_id:

            flash("You already have a Widget with the name '" + widget_name
                  + "'. Please try a different name as Widget names are unique.")

            keep_widget = get_widget_from_request(request)
            return render_template('edit_widget.html', widget=keep_widget)

    widget = {}
    widget['widget_name'] = widget_name
    widget['user_id'] = user_id
    widget['user_email'] = user_email
    widget['description'] = description

    db.update('widgets', {'widget_id': widget_id}, widget)

    flash("Widget '" + widget_name + "' edit successful.")

    log.debug('widget.py::edit_widget_complete',
              'Successful edit of existing widget, widget_id [' + widget_id + '].')

    return redirect(url_for('widget.my_widgets'))


def replace_widget(widgets, new_widget):
    """
    Replace a widget in a widget list.
    """

    for pos, current_widget in enumerate(widgets):

        if current_widget['widget_id'] == new_widget['widget_id']:
            widgets[pos] = new_widget

templates/about.html
{% extends "base.html" %}
{% block content %}
<b>About</b>
{% endblock %}

templates/add_widget.html
{% extends "base.html" %}
{% block content %}

<h3>Add a new widget</h3>
<hr>

<form id="f-add" class="pure-form pure-form-aligned" method="post" action={{ url_for('widget.add_widget_complete') }}>
  <fieldset>

    <div class="pure-control-group">
        <label for="widget_name">Widget name</label>
        <input name="widget_name" id="widget_name" type="text" placeholder="widget name" required value="{% if widget['widget_name'] is not none %}{{ widget['widget_name'] }}{% endif %}">
    </div>

    <div class="pure-control-group">
        <label for="description">Description</label>
        <input name="description" id="description" type="text" placeholder="description" required value="{% if widget['description'] is not none %}{{ widget['description'] }}{% endif %}">
    </div>

    <br/>
    <div class="pure-control-group">
        <button type="submit" class="pure-button pure-button-primary">add</button>
    </div>

  </fieldset>
</form>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>MyApp</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pure-min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='quantumrocket.css') }}" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>


<body>
    
    <div class="pure-g">
    <div class="pure-u-1-24"></div>
    <div class="pure-u-11-12">
        
    <p>
		<div class="pure-menu pure-menu-horizontal">
		<ul class="pure-menu-list">
			<li class="pure-menu-item"><a href="{{ url_for('home.index') }}" class="pure-menu-link">MyApp</a>
        	{% if session['authenticated'] %}
          	<li class="pure-menu-item"><a href="{{ url_for('home.dashboard') }}" class="pure-menu-link">Dashboard</a></li>
          	<li class="pure-menu-item"><a href="{{ url_for('widget.my_widgets') }}" class="pure-menu-link">Widgets</a></li>
			<li class="pure-menu-item"><a href="{{ url_for('profile.my_profile') }}" class="pure-menu-link">Profile</a></li>
			<li class="pure-menu-item"><a href="{{ url_for('home.sign_out') }}" class="pure-menu-link">Sign out</a></li>
        	{% endif %}
		</ul>
		</div>
    </p>

    <div id="flash" class="flash">
    	{% with messages = get_flashed_messages() %}
    		{% if messages %}
    			<ul class="flash">
    				{% for message in messages %}
    					<li>{{ message }}</li>
    				{% endfor %}
    			</ul>
    		{% endif %}
    	{% endwith %}
    </div>


    <div id="content">{% block content %}{% endblock %}</div>
    <div id="footer">QuantumRocket &copy; 2018</div>
    <br>
    
    </div>  <!-- pure-u-11-12 -->
    <div class="pure-u-1-24"></div>
    </div>

</body>

</html>

templates/dashboard.html
{% extends "base.html" %}
{% block content %}
<div>

<h3>Dashboard</h3>
<div class="help">{% if things['pref_show_page_help'] == 'yes' %}{{ things['page.dashboard.help']|safe }}{% endif %}</div>

<br>
<hr>

<h4>Widgets <span class="pure-form-message-inline">(Details go here.)</span></h4>
<table class="pure-table pure-table-horizontal">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        {% if widgets is none %}
            <tr><td colspan="7"><i>There are no widgets.</i></td></tr>
        {% else %}
            {% for widget in widgets %}
                <tr>
                    <td>{{ widget['widget_name'] }}</td>
                    <td>{{ widget['description'] }}</td>
                </tr>
            {% endfor %}
        {% endif %}
    </tbody>
</table>

<br>

</div>

<br><br>
{% endblock %}

templates/edit_widget.html
{% extends "base.html" %}
{% block content %}
<div>
<h3>Edit Widget</h3>
<hr>

<form id="f-edit-widget" class="pure-form pure-form-aligned" method="POST" action={{ url_for('widget.edit_widget_complete') }}>
  <fieldset>

    <input hidden name="widget_id" id="widget_id" type="text" value="{{ widget['widget_id'] }}">

    <div class="pure-control-group">
        <label for="widget_name">Widget name</label>
        <input name="widget_name" id="widget_name" type="text" placeholder="widget name" required value="{% if widget['widget_name'] is not none %}{{ widget['widget_name'] }}{% endif %}">
    </div>

    <div class="pure-control-group">
        <label for="description">Description</label>
        <input name="description" id="description" type="text" placeholder="description" required value="{% if widget['description'] is not none %}{{ widget['description'] }}{% endif %}">
    </div>

    <br/>
    <div class="pure-control-group">
        <button type="submit" class="pure-button pure-button-primary">save changes</button>
    </div>

  </fieldset>
</form>
</div>

<br><br>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
<div>
    <h3>Flask app</h3>
	<div class="help">{% if things['pref_show_page_help'] == 'yes' %}{{ things['page.index.help']|safe }}{% endif %}</div>
    <hr>

    {% if not session['authenticated'] %}
      <p>Already a user? Please sign in</p>

      <form class="pure-form pure-form-aligned" method="post" action={{ url_for('home.sign_in') }}>
          <fieldset>
            <div class="pure-control-group">
  	            <label for="user_email">Email address</label>
  	            <input name="user_email" id="user_email" type="email" placeholder="me@example.com" required value="a@a.a">
  	        </div>

            <div class="pure-control-group">
  	            <label for="password">Password</label>
  	            <input name="password" id="password" type="password" placeholder="your password" required value="a">
  	        </div>

              <button type="submit" class="pure-button pure-button-primary">Sign in</button>
          </fieldset>
      </form>

	  <br>
      <p>Sign up here...</p>

      <form class="pure-form pure-form-aligned" method="post" action={{ url_for('home.sign_up') }}>
          <fieldset>
            <div class="pure-control-group">
  	            <label for="user_email">Email address</label>
  	            <input name="user_email" id="user_email" type="email" placeholder="me@example.com" required value="a@a.a">
  	        </div>

            <div class="pure-control-group">
  	            <label for="password">Password</label>
  	            <input name="password" id="password" type="password" placeholder="your password" required value="a">
  	        </div>

              <button type="submit" class="pure-button pure-button-primary">Sign up</button>
          </fieldset>
      </form>
	{% else %}
      <br><br>
	  Good to see you again{% if user %} {{ user['full_name'] }}{% endif %}!
      <br><br>
    {% endif %}

</div>

<br><br>

{% endblock %}

templates/my_profile.html
{% extends "base.html" %}
{% block content %}
<div>
<h3>Profile</h3>
<div class="help">{% if things['pref_show_page_help'] == 'yes' %}{{ things['page.my_profile.help']|safe }}{% endif %}</div>
<hr>

<form id="f-info" class="pure-form pure-form-aligned" method="post" action={{ url_for('profile.update_profile') }}>
  <fieldset>
    <h4>My info</h4>

    <input hidden name="user_id" id="user_id" type="text" value="{{ user.user_id }}">

    <div class="pure-control-group">
        <label for="full_name">Full name</label>
        <input name="full_name" id="full_name" type="text" placeholder="full name" required value="{{ user.full_name }}">
    </div>

    <div class="pure-control-group">
        <label for="email">Email</label>
        <input name="email" id="email" type="text" placeholder="email address" required value="{{ user.display_email }}">
    </div>

    <div class="pure-control-group">
        <label for="phone">Phone</label>
        <input name="phone" id="phone" type="text" placeholder="phone number" value="{{ user.phone }}">
    </div>

    <br>
    <h4>App preferences</h4>

    <div class="pure-control-group">
        <label for="pref_show_page_help">Show page help</label>
	     <input type="checkbox" id="pref_show_page_help" name="pref_show_page_help" value="{{ user['pref_show_page_help'] }}"{% if user['pref_show_page_help'] == 'yes' %} checked{% endif %}></input>
         <span class="pure-form-message-inline">Check this box to see help text at the top of each page.<br>Help text is displayed with a yellow background.</span>
    </div>

    <br/>
    <div class="pure-control-group">
        <label for="update"></label>
        <button type="submit" class="pure-button pure-button-primary">update profile</button>
    </div>

  </fieldset>
</form>

</div>
<br>
<br>

{% endblock %}

templates/my_widgets.html
{% extends "base.html" %}
{% block content %}
<div>
<h3>Widgets</h3>
<div class="help">{% if things['pref_show_page_help'] == 'yes' %}{{ things['page.my_widgets.help']|safe }}{% endif %}</div>
<hr>

<h4>Widgets</h4>
<table class="pure-table pure-table-horizontal">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th align="center" colspan="2">Action</th>
        </tr>
    </thead>
    <tbody>
        {% if widgets is none %}
            <tr><td colspan="10"><i>No widgets have been defined. Click the 'Add new Widget' button below to add a new widget.</i></td></tr>
        {% else %}
            {% for widget in widgets %}
                <tr>
                    <td>{{ widget['widget_name'] }}</td>
                    <td>{{ widget['description'] }}</td>

                    <td>
                        <form id="f-edit" method="GET" action="{{ url_for('widget.edit_widget') }}">
                            <input hidden name="widget_id" id="widget_id" type="text" value="{{ widget['widget_id'] }}">
                            <button id="b-edit-{{ widget['widget_id'] }}" class="button-xsmall pure-button">edit</button>
                        </form>
                    </td>

                    <td>
                        <form id="f-delete" method="POST" action="{{ url_for('widget.delete_widget') }}">
                            <input hidden name="widget_id" id="widget_id" type="text" value="{{ widget['widget_id'] }}">
                            <button id="b-delete-{{ widget['widget_id'] }}" class="button-xsmall pure-button">delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        {% endif %}
    </tbody>
</table>

<br>
<table>
	<tr>
		<td>
		    <form id="f-add-widget" method="get" action="{{ url_for('widget.add_widget') }}">
			    <button id="b-add-widget" class="pure-button pure-button-primary">add new widget</button>
			</form>
		</td>
	</tr>
</table>

</div>

<br><br>

{% endblock %}

templates/terms.html
{% extends "base.html" %}
{% block content %}
<b>Terms Of Service</b>
{% endblock %}